#!/usr/bin/env bash
#
# Provision script for the "coding-agent" application — a self-hosted,
# OpenAI-compatible vLLM endpoint for agentic coding clients (our own VS
# Code extension, Cline, Continue, Aider, the OpenAI SDK, curl, etc.).
#
# Runs on the GPU instance after the container starts. The customer app's
# onstart wrapper exports these env vars before invoking us:
#
#   CC_PROVISION_URL      POST endpoint for stage updates
#                         (e.g. https://app.cloudcompute.ru/api/agent/provision)
#   CC_AGENT_TOKEN        bearer token authenticating us to that endpoint
#   CC_VLLM_API_KEY       the API key vLLM must require on every request.
#                         GENERATED BY THE CUSTOMER APP at launch and
#                         pre-seeded onto provision_state.api_key, so the
#                         dashboard already shows it before we even boot.
#                         We must serve with exactly this key. If absent
#                         (manual/local run) we mint a throwaway one.
#   CC_SERVED_MODEL_NAME  the `--served-model-name` to expose; the value the
#                         user pastes into their client as `model:`. The app
#                         pre-seeds provision_state.model_name from the same
#                         source, so the two always match.
#
# CC_PROVISION_URL / CC_AGENT_TOKEN are optional — if absent, report_stage
# is a silent no-op so the script still works for local manual testing
# (e.g. `bash provision.sh` inside a fresh container).
#
# Stage IDs reported here MUST match the application's provisioning.stages
# in config/applications.php. The customer app owns the API key and model
# name, so the final stage (open_tunnel) reports ONLY tunnel_url back —
# api_key / model_name are NOT sent (the app is the source of truth and
# already has them). The sticky-merge in AgentProvisionController keeps the
# pre-seeded values across our stage updates.
#
# NOTE on the lack of a max_model_len proxy: the sibling cursor-llm app
# ships a small proxy (proxy.py) that advertises a smaller max_model_len
# than vLLM enforces, because Cursor reads /v1/models and overshoots the
# context cap by +1 token every request. That is a Cursor-specific bug.
# coding-agent targets VS Code agents (Cline et al.) that respect the
# advertised cap, so we serve vLLM directly on the public port — no proxy,
# no internal/public port split.

set -euo pipefail

CC_PROVISION_URL="${CC_PROVISION_URL:-}"
CC_AGENT_TOKEN="${CC_AGENT_TOKEN:-}"

# Tracks the stage we last *entered* so the trap-ERR handler below can
# attribute an unexpected failure to the right manifest stage. Updated by
# report_stage on every call. Initialized to the first stage so a crash
# during the very first lines (before report_stage runs) still has a sane
# stage to report.
CC_CURRENT_STAGE="install_runtime"

# Model + serving config. Defaults target Qwen2.5-Coder-32B AWQ — a 32B-class
# coding model quantized to INT4, peaks at ~22 GB VRAM, runs comfortably on a
# single RTX 4090 / A6000. MODEL_ID can be overridden by exporting it before
# invoking the script (e.g. to test a 7B variant on a smaller card).
MODEL_ID="${MODEL_ID:-Qwen/Qwen2.5-Coder-32B-Instruct-AWQ}"

# The name clients send in the request body. The customer app pre-seeds this
# (CC_SERVED_MODEL_NAME) so the served name matches what the dashboard shows.
# We expose a short stable name regardless of which checkpoint is loaded, so
# switching MODEL_ID later doesn't break user-saved client settings. Falls
# back to the app's default short id when run manually.
SERVED_MODEL_NAME="${CC_SERVED_MODEL_NAME:-${SERVED_MODEL_NAME:-qwen2.5-coder-32b}}"

# Public port — what cloudflared exposes and what the client talks to.
# vLLM binds this directly (no proxy in front, unlike cursor-llm).
VLLM_PORT="${VLLM_PORT:-8000}"

# vLLM `--max-model-len` cap on per-request prompt+completion tokens, chosen
# by GPU VRAM. Agentic coding clients stuff a lot of file/context into the
# prompt, so a bigger window is better when the card can afford it.
#
# Per-token KV cache for Qwen 2.5 32B (GQA, 64 layers x 8 KV heads x 128
# head_dim x fp16) ~= 256 KiB. The model itself is ~18 GiB AWQ INT4. Budget
# remaining at gpu_memory_utilization 0.92 is roughly (vram_gib x 0.92) - 18;
# one full request needs max_len x 256 KiB.
#
#   24 GiB card  -> ~4 GiB KV -> ~16k tokens KV total -> 16k cap is the hard
#                   ceiling. YaRN-extending here would make vLLM refuse to
#                   even start up.
#   40 GiB+      -> ~18 GiB+ KV -> can hold a 65k single request comfortably.
#
# 65k is reached via YaRN x2 RoPE scaling (Qwen's native context is 32k;
# beyond that requires explicit YaRN config + the
# VLLM_ALLOW_LONG_MAX_MODEL_LEN=1 escape hatch — vLLM refuses the bigger
# max-model-len without it because un-scaled RoPE produces NaN past
# max_position_embeddings). Quality cost on Qwen 2.5 32B in the 32k-64k
# range is ~3-5%, well below what subjective coding usage notices.
#
# Detected via nvidia-smi at runtime so a single provision.sh works on the
# whole GPU lineup the customer-app filter (min_vram_gb=24) lands us on.
if command -v nvidia-smi >/dev/null 2>&1; then
    GPU_VRAM_MB=$(nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits 2>/dev/null | head -1 || echo 0)
else
    GPU_VRAM_MB=0
fi
if [ "${GPU_VRAM_MB:-0}" -ge 38000 ]; then
    MAX_MODEL_LEN_DEFAULT=65536
    YARN_NEEDED=1
else
    MAX_MODEL_LEN_DEFAULT=16384
    YARN_NEEDED=0
fi
MAX_MODEL_LEN="${MAX_MODEL_LEN:-$MAX_MODEL_LEN_DEFAULT}"

# Build the YaRN args conditionally — passing rope_scaling on a native-context
# launch (<= 32k) is harmless but the VLLM_ALLOW_LONG_MAX_MODEL_LEN env is
# only meaningful when we actually exceed max_position_embeddings. Keep both
# gated to the extended-context path so the 24 GiB launch line stays minimal.
EXTRA_VLLM_ARGS=()
if [ "$YARN_NEEDED" = "1" ]; then
    export VLLM_ALLOW_LONG_MAX_MODEL_LEN=1
    EXTRA_VLLM_ARGS+=(
        --hf-overrides
        '{"rope_scaling":{"rope_type":"yarn","factor":2.0,"original_max_position_embeddings":32768}}'
    )
fi

# Where vLLM and supporting tooling get installed. /workspace persists across
# Vast container restarts where /root does not, so prefer /workspace when it
# exists.
WORKDIR="${WORKDIR:-/workspace}"
mkdir -p "$WORKDIR"
LOG_DIR="${LOG_DIR:-/var/log}"
mkdir -p "$LOG_DIR"

VLLM_LOG="${LOG_DIR}/vllm.log"
TUNNEL_LOG="${LOG_DIR}/cloudflared.log"

# --- helpers --------------------------------------------------------------

# report_stage <stage_id> [extra_json_kv_pairs...]
#
# Best-effort POST to /api/agent/provision. The first arg is the stage id.
# Any remaining args are pre-formatted JSON key:value pairs that get
# concatenated into the body (e.g. `report_stage download_model
# '"progress_pct":42'`). Failures (network blips, 401, 422) are swallowed:
# a missed update is far preferable to crashing provisioning halfway
# through.
report_stage() {
    local stage="$1"
    shift
    # Always update the stage tracker, even when reporting is disabled (no
    # env vars). The trap-ERR handler still needs an accurate stage for its
    # own log line in that case.
    CC_CURRENT_STAGE="$stage"

    if [ -z "$CC_PROVISION_URL" ] || [ -z "$CC_AGENT_TOKEN" ]; then
        return 0
    fi
    local extra=""
    for kv in "$@"; do
        extra="${extra},${kv}"
    done
    curl -fsS \
        -X POST "$CC_PROVISION_URL" \
        -H "Authorization: Bearer $CC_AGENT_TOKEN" \
        -H "Content-Type: application/json" \
        -d "{\"stage\":\"${stage}\"${extra}}" \
        --max-time 5 \
        >/dev/null 2>&1 || true
}

log() {
    echo "[cc-provision] $*"
}

# Sanitize an arbitrary string for inlining into a JSON value: strip CR, fold
# newlines to spaces, and replace double-quotes with single-quotes. Use this
# on every dynamic substring (log tails, error messages, command names)
# before splicing into a `"message":"..."` payload, otherwise a stray quote
# in the source produces invalid JSON and AgentProvisionController 422s the
# request.
json_escape() {
    printf '%s' "$1" | tr -d '\r' | tr '\n' ' ' | sed 's/"/'"'"'/g'
}

# trap-ERR handler — fires for any command that fails under `set -e` and
# wasn't already handled with explicit `report_stage ... "\"message\":...\""`
# + `exit 1`. Without this, an unexpected failure (e.g. `pip install` 503,
# `mkdir -p` on a read-only mount, a shell typo we never hit in testing)
# kills the script silently. The backend then has nothing on
# `provision_state.message` and only the 30-min OVERALL_TIMEOUT eventually
# flips the instance to ERROR — a window where the user is billed for
# nothing.
#
# Behaviour:
#   1. Disable the trap immediately to prevent recursion if anything inside
#      the handler also fails.
#   2. Capture exit code, line, and the command text BEFORE doing any other
#      work (later commands would clobber $? / $BASH_COMMAND).
#   3. POST a fatal `message` tagged to CC_CURRENT_STAGE. The customer app's
#      provisioning-failed predicate picks this up on the next polling tick
#      and flips the instance to ERROR with a clear message in seconds, not
#      30 minutes.
#   4. Re-exit with the original code so anything downstream observes the
#      same failure.
handle_uncaught_error() {
    local exit_code=$?
    trap - ERR

    local line_no="${1:-?}"
    local command_text
    command_text="$(json_escape "${2:-?}")"

    log "uncaught error at line ${line_no} (stage=${CC_CURRENT_STAGE}, exit=${exit_code}): ${2:-?}"

    report_stage "$CC_CURRENT_STAGE" \
        "\"message\":\"Скрипт упал на line ${line_no}: ${command_text} (exit ${exit_code})\""

    # Bash treats `exit 0` as success, but we got here BECAUSE something
    # failed — fall back to 1 if the captured code somehow ended up 0.
    if [ "$exit_code" -eq 0 ]; then
        exit_code=1
    fi
    exit "$exit_code"
}
trap 'handle_uncaught_error "$LINENO" "$BASH_COMMAND"' ERR

# The API key the app generated for this instance. The customer app exports
# it as CC_VLLM_API_KEY and already shows it on the dashboard; we serve with
# exactly that key so the dashboard card works without us reporting anything.
# Fallback: when run manually (no app), mint a throwaway sk-cc-<hex> key so
# the server still requires auth. /dev/urandom is the most portable source
# (openssl isn't always present on slimmed-down vLLM images).
fallback_api_key() {
    if command -v xxd >/dev/null 2>&1; then
        printf 'sk-cc-%s' "$(head -c 16 /dev/urandom | xxd -p -c 32)"
    else
        printf 'sk-cc-%s' "$(head -c 16 /dev/urandom | od -An -tx1 | tr -d ' \n')"
    fi
}

API_KEY="${CC_VLLM_API_KEY:-$(fallback_api_key)}"

# --- stage 1: install_runtime --------------------------------------------

log "stage: install_runtime"
report_stage install_runtime

# vLLM. The Vast `vllm` template ships with vLLM preinstalled, but we still
# `pip install -U` to make sure we pick up bugfixes the template hasn't been
# rebuilt for yet. Pip is a no-op when versions match. On a non-vLLM base
# image this is what actually installs vLLM (~5 min cold install).
pip install --no-cache-dir -U "vllm>=0.6.0" >/dev/null

# cloudflared: standalone static binary, no apt repo needed. ~30 MB. Used to
# open a free trycloudflare.com quick tunnel that gives us a public HTTPS URL
# pointing at localhost:VLLM_PORT — coding clients' "Add custom model" UIs
# require HTTPS, which Vast.ai's raw <ip>:<port> mappings can't provide.
CLOUDFLARED_BIN="/usr/local/bin/cloudflared"
if ! [ -x "$CLOUDFLARED_BIN" ]; then
    log "installing cloudflared"
    # amd64 is the only arch Vast.ai hosts use today; if that ever changes
    # we'll need to detect uname -m. Pin to a known-stable release rather
    # than 'latest' so the script is reproducible.
    curl -fsSL \
        "https://github.com/cloudflare/cloudflared/releases/download/2024.10.0/cloudflared-linux-amd64" \
        -o "$CLOUDFLARED_BIN"
    chmod +x "$CLOUDFLARED_BIN"
fi

# Kill any pre-existing process holding VLLM_PORT — the upstream Vast vllm
# template autostarts its own vLLM with a default model on first boot
# (DeepSeek-R1-Distill-Llama-8B at the time of writing). Without this we'd
# fail to bind 8000 and spend ages debugging. fuser exits non-zero when
# nothing's bound, hence the `|| true`.
log "freeing port ${VLLM_PORT} if held by another process"
fuser -k "${VLLM_PORT}/tcp" 2>/dev/null || true
sleep 2

# --- stage 2: download_model ---------------------------------------------
#
# vLLM auto-downloads weights from HuggingFace the first time you reference a
# HF model id. There's no good way to grab a percentage from inside the vLLM
# startup so we report a coarse 0%/100% transition. The model is ~20 GB; on a
# Vast host with a 500+ Mbps uplink (we filter for these in
# ApplicationsController) it takes ~5-7 minutes.

log "stage: download_model"
report_stage download_model '"progress_pct":0'

# Pre-download via huggingface-hub so we can decouple "weights on disk" from
# "vLLM startup" — that way if the model download fails we report it at the
# right stage, instead of having the user see a confusing "starting server"
# failure that actually originated in HF.
pip install --no-cache-dir -U "huggingface_hub[cli]>=0.26.0" >/dev/null

HF_HOME="${HF_HOME:-${WORKDIR}/hf-cache}"
mkdir -p "$HF_HOME"
export HF_HOME

if ! huggingface-cli download "$MODEL_ID" \
    --cache-dir "$HF_HOME" \
    > "${LOG_DIR}/hf-download.log" 2>&1; then
    log "huggingface-cli download failed; see ${LOG_DIR}/hf-download.log"
    tail_msg="$(json_escape "$(tail -c 400 "${LOG_DIR}/hf-download.log")")"
    report_stage download_model "\"message\":\"HF download failed: ${tail_msg}\""
    exit 1
fi

report_stage download_model '"progress_pct":100'

# --- stage 3: start_server -----------------------------------------------

log "stage: start_server"
report_stage start_server

# Launch vLLM as a background process. Key flags:
#   --api-key                 : require Authorization: Bearer <key> on every request
#                               (this is the app-generated CC_VLLM_API_KEY)
#   --served-model-name       : the model identifier clients see (decoupled from $MODEL_ID)
#   --max-model-len           : 16k on 24 GiB cards, 65k (YaRN x2) on 40 GiB+ —
#                               see MAX_MODEL_LEN auto-detect block above.
#   --gpu-memory-utilization  : 0.92 — squeeze ~2 extra GiB of KV cache out of
#                               every host; AWQ kernels + cloudflared still fit.
#   --quantization awq_marlin : faster AWQ inference path on Ampere/Ada/Hopper.
#   --enable-auto-tool-choice + --tool-call-parser hermes :
#       Lets clients that use native OpenAI tool/function calling send
#       `tool_choice: "auto"` without vLLM 400ing the request
#       ('"auto" tool choice requires --enable-auto-tool-choice and
#       --tool-call-parser to be set'). Qwen 2.5 (incl. Coder) emits tool
#       calls in the Hermes / ChatML <tool_call> format, so `hermes` is the
#       correct parser. Harmless for prompt-based agents like Cline (the
#       parser only kicks in when the model actually emits a <tool_call>),
#       so there's no downside — it just adds capability for clients that
#       want native tool calling.
nohup vllm serve "$MODEL_ID" \
    --host 0.0.0.0 \
    --port "$VLLM_PORT" \
    --api-key "$API_KEY" \
    --served-model-name "$SERVED_MODEL_NAME" \
    --max-model-len "$MAX_MODEL_LEN" \
    --gpu-memory-utilization 0.92 \
    --quantization awq_marlin \
    --enable-auto-tool-choice \
    --tool-call-parser hermes \
    "${EXTRA_VLLM_ARGS[@]}" \
    > "$VLLM_LOG" 2>&1 &
VLLM_PID=$!

# Wait for vLLM to bind the port. Loading + quantizing 32B AWQ + warming the
# kernel takes 60-180s on a 4090. Bail early if the process dies.
VLLM_BIND_TIMEOUT_S=300
for _ in $(seq 1 "$VLLM_BIND_TIMEOUT_S"); do
    if curl -fsS --max-time 1 "http://127.0.0.1:${VLLM_PORT}/v1/models" \
        -H "Authorization: Bearer ${API_KEY}" >/dev/null 2>&1; then
        log "vLLM ready on port ${VLLM_PORT}"
        break
    fi
    if ! kill -0 "$VLLM_PID" 2>/dev/null; then
        log "vLLM exited before binding port ${VLLM_PORT}"
        tail_msg="$(json_escape "$(tail -c 500 "$VLLM_LOG")")"
        report_stage start_server "\"message\":\"vLLM crashed during startup: ${tail_msg}\""
        exit 1
    fi
    sleep 1
done

if ! kill -0 "$VLLM_PID" 2>/dev/null; then
    report_stage start_server "\"message\":\"vLLM died before completing startup\""
    exit 1
fi

# --- stage 4: open_tunnel ------------------------------------------------
#
# Cloudflare quick tunnel: free, no signup, no DNS. cloudflared connects
# outbound to Cloudflare's edge and gets back a random
# https://<words>.trycloudflare.com URL that proxies to our local VLLM_PORT.
#
# trycloudflare.com aggressively rate-limits new tunnel registrations from
# the same egress IP — Vast hosts can hit HTTP 429 / Error 1015 within
# seconds when the same datacenter recently spun up several quick tunnels.
# The retry loop below ABSORBS those 429s with exponential backoff instead
# of failing the whole instance launch. Tunnel creation is idempotent on
# Cloudflare's side; each attempt gets a fresh URL.

log "stage: open_tunnel"
report_stage open_tunnel

TUNNEL_URL=""
# Per-attempt cap: long enough for cloudflared to either succeed or reveal a
# 429, short enough that 4 attempts x this + backoff still fits comfortably
# under the customer-app overall provisioning timeout (30 min).
TUNNEL_ATTEMPT_TIMEOUT_S=60
TUNNEL_MAX_ATTEMPTS=4

# open_tunnel_attempt — runs cloudflared once, watches its log, returns:
#   0  TUNNEL_URL set and TUNNEL_PID exported
#   1  process died / no URL — caller may retry
#   2  HTTP 429 / rate-limited — caller MUST back off before retrying
open_tunnel_attempt() {
    : > "$TUNNEL_LOG"

    nohup "$CLOUDFLARED_BIN" tunnel \
        --no-autoupdate \
        --url "http://localhost:${VLLM_PORT}" \
        > "$TUNNEL_LOG" 2>&1 &
    local pid=$!

    local elapsed=0
    while [ "$elapsed" -lt "$TUNNEL_ATTEMPT_TIMEOUT_S" ]; do
        local candidate
        candidate="$(grep -oE 'https://[a-z0-9-]+\.trycloudflare\.com' "$TUNNEL_LOG" 2>/dev/null | head -n 1 || true)"
        if [ -n "$candidate" ]; then
            TUNNEL_URL="$candidate"
            TUNNEL_PID="$pid"
            return 0
        fi

        # 429 detection: cloudflared logs include "error code: 1015" and
        # "429" in different lines depending on Cloudflare's response. Match
        # either token to avoid relying on exact phrasing across versions.
        if grep -qE '(\b429\b|Too Many Requests|error code: ?1015)' "$TUNNEL_LOG" 2>/dev/null; then
            log "cloudflared rate-limited (HTTP 429) on attempt"
            kill "$pid" 2>/dev/null || true
            wait "$pid" 2>/dev/null || true
            return 2
        fi

        if ! kill -0 "$pid" 2>/dev/null; then
            log "cloudflared exited on attempt"
            return 1
        fi

        sleep 1
        elapsed=$((elapsed + 1))
    done

    # Timed out without URL or 429: kill and let caller retry.
    log "cloudflared attempt timed out without URL"
    kill "$pid" 2>/dev/null || true
    wait "$pid" 2>/dev/null || true
    return 1
}

# Suppress both `set -e` AND the ERR trap for the retry block — we want a
# non-zero return from open_tunnel_attempt to drive our retry/backoff logic,
# NOT to kill the script.
#
# Why both: `trap - ERR` alone is NOT enough. `set -e` is what causes the
# shell to exit on a non-zero return; the ERR trap is just the hook that
# fires before the exit. Without `set +e` here, the very first
# open_tunnel_attempt returning 2 (HTTP 429) immediately exits provision.sh —
# silently, with no report_stage ever sent — and the user sits at "open_tunnel"
# until the backend's overall timeout flips the instance to ERROR.
#
# Re-enable both on the way out so any subsequent failure still gets caught
# by the global fatal handler.
set +e
trap - ERR
TUNNEL_LAST_RC=1
for attempt in $(seq 1 "$TUNNEL_MAX_ATTEMPTS"); do
    log "cloudflared attempt ${attempt}/${TUNNEL_MAX_ATTEMPTS}"

    open_tunnel_attempt
    TUNNEL_LAST_RC=$?

    if [ "$TUNNEL_LAST_RC" -eq 0 ]; then
        break
    fi

    if [ "$attempt" -lt "$TUNNEL_MAX_ATTEMPTS" ]; then
        # Exponential backoff for 429 (trycloudflare hates this egress IP
        # right now — needs real wall-clock time), linear for generic
        # failures (usually recover on the next attempt).
        if [ "$TUNNEL_LAST_RC" -eq 2 ]; then
            sleep_for=$((30 * attempt))
        else
            sleep_for=$((5 * attempt))
        fi
        log "backing off ${sleep_for}s before retry"
        sleep "$sleep_for"
    fi
done
set -e
trap 'handle_uncaught_error "$LINENO" "$BASH_COMMAND"' ERR

if [ -z "$TUNNEL_URL" ]; then
    tail_msg="$(json_escape "$(tail -c 400 "$TUNNEL_LOG" 2>/dev/null || true)")"
    if [ "$TUNNEL_LAST_RC" -eq 2 ]; then
        report_stage open_tunnel "\"message\":\"cloudflared rate-limited (HTTP 429) by trycloudflare.com after ${TUNNEL_MAX_ATTEMPTS} retries: ${tail_msg}\""
    else
        report_stage open_tunnel "\"message\":\"cloudflared failed after ${TUNNEL_MAX_ATTEMPTS} retries: ${tail_msg}\""
    fi
    exit 1
fi

log "tunnel URL: ${TUNNEL_URL}"

# Final report: ship ONLY the tunnel_url the customer-app UI needs to finish
# the connect card. api_key + model_name are owned by the app (pre-seeded on
# provision_state at launch) so we deliberately do not resend them.
# progress_pct:100 on the final stage is what tells the controller the
# application is fully provisioned (see AgentProvisionController). We escape
# any quote in the URL defensively, although cloudflared output is
# guaranteed-safe today.
escape_json() {
    printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}
TUNNEL_URL_JSON="$(escape_json "$TUNNEL_URL")"

report_stage open_tunnel \
    '"progress_pct":100' \
    "\"tunnel_url\":\"${TUNNEL_URL_JSON}\""

log "provisioning complete"
log "  tunnel: ${TUNNEL_URL}"
log "  api key: ${API_KEY} (owned by the customer app)"
log "  model name: ${SERVED_MODEL_NAME}"
log "  max_model_len: ${MAX_MODEL_LEN} (GPU VRAM ${GPU_VRAM_MB} MB, YaRN=${YARN_NEEDED})"
log "vLLM PID: ${VLLM_PID}; cloudflared PID: ${TUNNEL_PID:-?}"
exit 0
